# SPDX-FileCopyrightText: 2025 Jason Pena <jasonpena@awkless.com>
# SPDX-License-Identifier: MIT

[graph]
all-features = true

[advisories]
version = 2

[bans]
multiple-versions = "deny"
wildcards = "deny"
skip = [
  { name = "regex-automata", version = "0.1.10" },
  { name = "regex-syntax", version = "0.6.29" },
  { name = "windows-sys", version = "0.52.0" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[licenses]
confidence-threshold = 0.8
allow = [
  "Apache-2.0",
  "MIT",
  "Unicode-3.0",
  "MPL-2.0",
]
