# SPDX-FileCopyrightText: 2025 Jason Pena <jasonpena@awkless.com>
# SPDX-License-Identifier: MIT

title: OCD Tool
description: Organize current dotfiles

remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
