.TH OCD-LS "1" "May 2025" "ocd 0.8.0" "User Commands"
.SH NAME
ocd \- list current entries in cluster
.SH SYNOPSIS
ocd list [options]
.SH DESCRIPTION
Pretty print a table containing all currently defined entries in the cluster
with some status information. User can also just request for only the names of
each entry instead.
.SH OPTIONS
.PP
\-n, \-\-names-only
.RS 4
Only list names of each entry only.
.RE
.PP
\-h, \-\-help
.RS 4
Prints help message for this command.
.RE
.SH OCD
Part of the \fBocd\fR(1) command-set.
