# SPDX-FileCopyrightText: 2025 Jason Pena <jasonpena@awkless.com>
# SPDX-License-Identifier: CC0-1.0

name: REUSE compliance check

on: [push, pull_request]

jobs:
  reuse-compliance-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: REUSE compliance check
        uses: fsfe/reuse-action@v5
